package com.uber.driveronboardingmanagement.interfaces.dtos.driver;

import org.springframework.hateoas.RepresentationModel;

import com.fasterxml.jackson.annotation.JsonUnwrapped;

/**
 * The DriverDto class is a data transfer object (DTO) that represents a single driver.
 * It inherits from the ResourceSupport class which allows us to create a REST representation (e.g., JSON, XML)
 * that follows the HATEOAS principle. For example, links can be added to the representation (e.g., self, vehicle.change)
 * which means that future actions the client may take can be discovered from the resource representation.
 *
 * The DriverDto is part of the API contract (see the getDriver() method in @DriverInformationHolder). In the Swagger API docs
 * (http://localhost:8090/v2/api-docs) generated by SpringFox the is represented by the following JSON Schema. JSON Schema (https://json-schema.org/)
 * is an IETF draft to define the schema of JSON documents:
 *
 * <pre>
 * <code>
 * {
 *  "title":"DriverDto",
 *  "type":"object",
 *  "properties":{
 *     // Note that this _links section of the JSON Schema appears here, because DriverDto
 *     // inherits from ResourceSupport which can add HATEOAS links to the JSON representation
 *     // of the resource.
 *     "_links":{
 *        "type":"array",
 *        "xml":{
 *           "name":"link",
 *           "attribute":false,
 *           "wrapped":false
 *        },
 *        "items":{
 *           "$ref":"#/definitions/Link"
 *        }
 *     },
 *     "birthday":{
 *        "type":"string",
 *        "format":"date-time"
 *     },
 *     "registeredCity":{
 *        "type":"string"
 *     },
 *     "driverId":{
 *        "type":"string"
 *     },
 *     "email":{
 *        "type":"string"
 *     },
 *     "firstname":{
 *        "type":"string"
 *     },
 *     "lastname":{
 *        "type":"string"
 *     },
 *     "vehicleList":{
 *        "type":"array",
 *        "items":{
 *           "$ref":"#/definitions/VehicleDto"
 *        }
 *     },
 *     "phoneNumber":{
 *        "type":"string"
 *     },
 *     "licensePlateNumber":{
 *        "type":"string"
 *     },
 *     "vehicleName":{
 *        "type":"string"
 *     }
 *  }
 * }
 * </code>
 * </pre>
 *
 * @see <a href="https://docs.spring.io/spring-hateoas/docs/current/reference/html/">Spring HATEOAS - Reference Documentation</a>
 */
public class DriverDto extends RepresentationModel {
	private String driverId;
	@JsonUnwrapped
	private DriverProfileDto driverProfile;

	public DriverDto() {
	}

	public DriverDto(String driverId, DriverProfileDto driverProfile) {
		this.driverId = driverId;
		this.driverProfile = driverProfile;
	}

	public String getDriverId() {
		return driverId;
	}

	public DriverProfileDto getDriverProfile() {
		return this.driverProfile;
	}

	public void setDriverId(String driverId) {
		this.driverId = driverId;
	}

	public void setDriverProfile(DriverProfileDto driverProfile) {
		this.driverProfile = driverProfile;
	}
}
